### ISSUE TITLE
Settings of Gravity Forms not saved

### ISSUE THREAD

**Issue by InfectedWeb** [soulseekah/Gravity-Forms-Saved-Forms-Addon#21]
Hi, if i make a check on "Enable form persistence" and save the settings, the check is gone. But only on this settings. Original settings from Gravity Forms are saved.

I use Gravity Form 1.8.8.10 and Wordpress 3.9.1

**Comment by soulseekah** [comment]
Closed due to lack of feedback. Reopen if still relevant with more information.
