### ISSUE TITLE
Save for later only showing on last step of multi-step form

### ISSUE THREAD

**Issue by abloomfield44** [soulseekah/Gravity-Forms-Saved-Forms-Addon#25]
I just changed to the Underscores (http://underscores.me) theme, which is very bare-bones. If I preview the form in Gravity Forms or switch to the TwentyFourteen theme, it shows fine on all steps. But on my theme, it's only appearing on the last step.

I inspected the code, and it's not there at all, until the last step (I wanted to rule out there being a css issue)

Anyone know what might be missing from that theme?

**Comment by soulseekah** [comment]
Amanda, can you update to https://github.com/soulseekah/Gravity-Forms-Saved-Forms-Addon/releases/tag/0.4.3.1 please and let me know how it goes? I moved some of the multipage logic around should work better.

**Comment by abloomfield44** [comment]
Wow thank you. This worked perfectly.
