### ISSUE TITLE
single form has multiple save buttons on page with multiple forms

### ISSUE THREAD

**Issue by nyladenise** [soulseekah/Gravity-Forms-Saved-Forms-Addon#26]
I have three different forms on a page, only one of which needs to allow the save for later option. It worked fine when it was the only form on the page, but once I added the other two, I now have three "save for later" buttons appearing on my first form. And the functionality is broken -- clicking any one of the "save for later" buttons only leads to a blank white screen.  Any thoughts?

**Comment by soulseekah** [comment]
Thanks for reporting this, I can imagine this happening easily. Will try to reproduce sometime next week and get a patch going I think.

**Comment by soulseekah** [comment]
I've had a short play with this today, I created three forms, added them onto one page, only the second form has the saved forms functionality switched on. Clicking it worked well. See screenshot below showing three steps - page initially, after pressing save, and loading page again.

![image](https://cloud.githubusercontent.com/assets/685880/5694983/34389e6e-99a7-11e4-968c-05ca8058e8e5.png)

Are you able to send me an Export of the forms you are using (gennady[at]kovshenin[dot]com)? Also are you using the latest version of this plugin? And what version of Gravity Forms?

I did produce a similar issue where the save buttons wouldn't appear on the other forms if save was enabled for them. Which I'll look into.

**Comment by soulseekah** [comment]
Forgot to turn on "Require Login" for the other two forms before testing multiple save. It worked well as the screenshot below shows, only the bottom form has save functionality disabled. You are probably running an old version of the plugin, as I recollect we've had similar issues here: https://github.com/soulseekah/Gravity-Forms-Saved-Forms-Addon/issues/24#issuecomment-53957498 try updating and get back to me. Thanks.

![image](https://cloud.githubusercontent.com/assets/685880/5694989/0fd0980a-99a8-11e4-86a4-c95f7a572c56.png)

**Comment by nyladenise** [comment]
Thanks for looking into it. To my knowledge, I am using the latest versions.  Grabbed the zip file from here only a day or so before I posted.
Version 0.4.3 of your plugin.
Version 1.8.2.0 of Gravity Forms.
Wordpress 4.1
I have emailed the export of my three forms.

**Comment by nyladenise** [comment]
Progress... maybe.  I had wrapped all three of my forms in single containing <form><fieldset> tag. Removing these tags allowed the buttons to work, however, I still have three save buttons showing on the one form.  

If I hit the "Next" button to go to the next page on my form, there is only one save button, as it should be. And if I then go back to the previous page on my form, there is only one save button, as it should be.

So it seems this problem happens when the form is initially loaded, but once a button is pushed, it corrects itself. Any idea why this could be?

**Comment by soulseekah** [comment]
Are you trying this on a default theme (one of the twenty* ones)? In one single post div or scattered across a number of post divs?

**Comment by nyladenise** [comment]
No, it's a custom theme, but I tested on Twenty Fifteen and no plugins enabled except the ones needed, still had the issue. How do I post code on here? I tried in my last reply and it was deleted from my response.

**Comment by soulseekah** [comment]
Send the post content by e-mail.

**Comment by soulseekah** [comment]
I have imported the forms and managed to reproduce the issue. Seems like it's an issue with forms with multiple pages on them, i.e. multiple forms with multiple pages on one page.

**Comment by soulseekah** [comment]
Here's a stab at fixing the issue: https://raw.githubusercontent.com/soulseekah/Gravity-Forms-Saved-Forms-Addon/229902159f552d0e98fb71eb3da5b8ea42bead35/gravityforms-savedforms/gravityforms-savedforms.js please download this file and replace gravityforms-savedforms/gravityforms-savedforms.js in your version, hard reload the browser (to clear all cached resources) and the issue should be gone. Let me know how it goes.

**Comment by soulseekah** [comment]
Actually scratch that, it was the old way of adding the button. I changed to a better way, so delete gravityforms-savedforms/gravityforms-savedforms.js  entirely and replace gravityforms-savedforms/gravityforms-savedforms.php with this file https://raw.githubusercontent.com/soulseekah/Gravity-Forms-Saved-Forms-Addon/0e596bf53efd5fc21076acb84d8e47ec381c42e7/gravityforms-savedforms/gravityforms-savedforms.php

Should work even better.

**Comment by nyladenise** [comment]
Works great. Thank you very much!

**Comment by soulseekah** [comment]
Excellent! I've pushed a new version tag with a couple of other important fixes for multiple forms on the same page. Feel free to update by downloading it here https://github.com/soulseekah/Gravity-Forms-Saved-Forms-Addon/releases/tag/0.4.3.1 and replacing all the files. Thanks a have a good one.
